version: "3.8"

services:
  megamedia:
    image: megamedia
    container_name: megamedia
    build: .
    ports: 
      - "8080"
    networks:
      - megagera_network

networks:
  megagera_network:
    external: true
